Algoritmo "Soma"
//Peça ao usuário para digitar três valores inteiros e imprima a soma deles.
Var
numero1:real
numero2:real
numero3 :real
soma: real


Inicio
Escreva("Digite o primeiro valor aqui:  ")
Leia(numero1)

Escreva("Digite o segundo valor aqui: ")
Leia(numero2)

Escreva("Digite o terceiro valor aqui: ")
Leia(numero3)

soma <- numero1 + numero2 + numero3
Escreva("O resultado da soma é: ",soma)




Fimalgoritmo